name: First Workflow
on: workflow_dispatch
jobs: 
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Hello Moon!"
      - name: Print Goodbye
        run: echo "Done"
